# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyproblog', '0003_auto_20170818_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
