# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyproblog', '0004_subscriber_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='active',
        ),
    ]
