# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyproblog', '0005_remove_subscriber_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('name',),
                'default_permissions': ['manage'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('to', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('-created_date',),
                'default_permissions': ['manage'],
            },
        ),
    ]
