# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyproblog', '0009_subscriber_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
