# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pyproblog', '0010_remove_subscriber_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
